### ISSUE TITLE
不能运行

### ISSUE THREAD

**Issue by zxp1314gch** [CxZMoE/netease-electron#1]
安装了之后直接打不开
![截图录屏_dde-control-center_20200625090931](https://user-images.githubusercontent.com/56782560/85642268-8a43f500-b680-11ea-9b9a-4b6251e28564.png)

**Comment by CxZMoE** [comment]
在程序根目录下
sudo chown root chrome-sandbox
chmod 4755 chrome-sandbox

**Comment by CxZMoE** [comment]
这个是linux内核的问题
修改内核参数也可以解决问题
sudo sysctl kernel.unprivileged_userns_clone=1
